web4-app/assignments/config/routes.rb
Rails.application.routes.draw do
  get 'contact/form'
  post 'contact/form', to: 'contact#create'
  root 'site#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'basics', to: 'basics#index'
  get 'admin/feedback'
  patch 'admin/feedback', to: 'admin#edit'
  delete 'admin/feedback', to: 'admin#destroy'
  get 'admin/committee'
  post 'admin/committee', to: 'admin#create'
  patch 'admin/committee', to: 'admin#edit'
  delete 'admin/committee', to: 'admin#destroy'
  get 'admin/users'
  patch 'admin/users'
  post 'admin/users'
  get 'problem-sets', to: 'site#problem_sets'
  get 'basics/news', to: 'basics#news'
  get 'basics/divide_by_zero', to: 'basics#divide_by_zero'
  get 'basics/divide', to: 'basics#divide'
  get 'basics/quotations', to: 'basics#quotations'
  post 'basics/quotations', to: 'basics#quotations'
  get 'basics/sql_tasks', to: 'basics#sql_tasks'
  get 'plan/index'
  get 'plan/profiles'
  get 'plan/user_management'
  get 'plan/documentation'
  get 'su_information', to: 'su_information#index'
  post 'su_information', to: 'su_information#create'
  patch 'su_information', to: 'su_information#edit'
  delete 'su_information', to: 'su_information#destroy'
  resources :events
  get 'past-events', to: 'events#past_events'
  get 'feedback', to: 'plan#feedback'
  post 'events/removeImage', to: "events#removeImage"
end

web4-app/assignments/app/models/event.rb
class Event < ApplicationRecord
    has_many_attached :pictures
    validates_presence_of :title
    validates_presence_of :description
    validates_presence_of :event_date
    belongs_to :tag, optional: true 
    paginates_per 9
end

web4-app/assignments/app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]

  def index
    @selected_tag = 0
    if params[:tag_id] and params[:tag_id].to_i != 0
      @selected_tag = params[:tag_id]
      @events = Event.where('event_date >= ? and tag_id = ?', Date.today, params[:tag_id]).order('event_date DESC').page(params[:page])
    else
      @events = Event.where('event_date >= ?', Date.today ).order('event_date DESC').page(params[:page])
    end
  end

  def new
    @event = Event.new
  end

  def create 
    @event = Event.new(event_params)
    if @event.save
      if params[:event][:pictures].present?
        params[:event][:pictures].each do |image|
          @event.pictures.attach(image)
        end
      end
      flash[:success] = 'Event created successfully'
      redirect_to events_path
    else
      render :new
    end
  end

  def past_events
    @selected_month = Time.now.month
    if params[:date] and params[:date][:month]
      @selected_month = params[:date][:month].to_i
    end
    @events = Event.where('extract(month from event_date) = ? and event_date < ?', @selected_month, Date.today()).order('event_date DESC').page(params[:page])
    
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        if params[:event][:pictures].present?
          params[:event][:pictures].each do |image|
            @event.pictures.attach(image)
          end
        end
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.pictures&.purge
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def removeImage
      p "Here"
      @picture = ActiveStorage::Attachment.find(params[:id])
      @picture.purge
      redirect_back(fallback_location: request.referer)
  end

  private
    def event_params
      params.require(:event).permit(:title, :description,:tag_id, :event_date)
    end

    def set_event
      @event = Event.find(params[:id])
    end
end

web4-app/assignments/app/helpers/events_helper.rb
module EventsHelper
end

web4-app/assignments/app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <ul>
        <li><%= @event.errors.first.full_message %></li>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-6">
      <%= form.label :title, class: 'form-label' %>
      <div class="form-outline mb-4">
        <%= form.text_field :title, class: 'input' %>
      </div>
    </div>
    <div class="col-md-6">
      <%= form.label :event_date, class: 'form-label' %>
      <div class="form-outline mb-4">
        <%= form.date_field :event_date, class: 'datepicker input' %>
      </div>
    </div>
  </div>
  <%= form.label :description, class: 'form-label' %>
  <div class="form-outline mb-4">
    <%= form.text_area :description, class: 'input', rows: '6' %>
  </div>
  <div class="row">
    <div class="col-md-2">
      <%= form.label :category, class: 'form-label' %>
    </div>
    <div class="col-md-4">
      <%= form.select( :tag_id, Tag.all.collect {|q| [ q.name, q.id] },{prompt: "Select Category" }, {class:"input"})%>
    </div>
  </div>
  <div class = "row col-12">
    <%= form.label :pictures, class: "col-sm-2 col-form-label" %>
    <div class="col-sm-8">
      <%= form.file_field :pictures, id: "uploaded-pictures", class:"input", multiple: true, accept: "image/*" %>
    </div>
    <div class = "col-sm-2">
      <button id= "removeImage" type="button" class="btn btn-danger" style="display:none;" >Remove</button>
    </div>
  </div>
  <div class="images"></div>
  <div class="preview-images">
  <% if event.pictures.present? %>
    <% event.pictures.map do |picture| %>
    <div>
        <%= image_tag(picture ,alt: "event_image")%>
        <%= link_to "Remove", events_removeImage_path(:id => picture.id), method: :post %>
    </div>
    <% end %>
  <% end %>
  </div>  
  <div class="modal-footer">
    <%= form.submit 'Submit', class: 'btn btn-su mb-4' %>
  </div>
<% end %>
<script>
  $(function () {
    // Multiple images preview in browser
    var imagesPreview = function (input, placeToInsertImagePreview) {
      console.log("inside image preview");
      const btn1 = document.getElementById("removeImage");
      $(placeToInsertImagePreview).html("");
      if (input.files) {
        var filesAmount = input.files.length;
  
        if (filesAmount > 0) {
          for (i = 0; i < filesAmount; i++) {
            var reader = new FileReader();
            var id = $(input.files[i]).attr("id");
            reader.onload = function(event) {
                  $($.parseHTML('<img >')).attr('src', event.target.result).appendTo(placeToInsertImagePreview);
              }
  
            reader.readAsDataURL(input.files[i]);
          }
          btn1.style.display = "block";
        } else {
          $(placeToInsertImagePreview).html("");
          btn1.style.display = "none";
        }
      }
    };
  
    $("#uploaded-pictures").on("change", function () {
      console.log("inside on change");
      imagesPreview(this, "div.images");
    });
    $("#removeImage").click(function (e) {
      e.preventDefault(); // prevent default action of link
      this.files = [];
      $("#uploaded-pictures").val(""); // clear image input value
      imagesPreview(this, "div.images");
    });
  });
  flatpickr(".datepicker", {enableTime: true})
</script>

web4-app/assignments/app/views/events/_list.html.erb
<div class = "container">
  <div class="row">
    <% if flash.any?%>
      <%= render 'layouts/alerts'%>
    <% end %>
    <% if @events.present? %>
      <section class="" id="meetings">
          <div class="row">
            <div class="col-lg-12">
              <div class="row">
                <% @events.each do |event| %>
                  <div class="col-lg-4">
                    <div class="meeting-item" id='<%= event.id%>'>
                      <div class="thumb">
                        <%= link_to  event_path(event) do%>
                          <% if event.pictures.attached? %>
                            <%= image_tag(event.pictures[0], alt: "event_image", class: 'events-list') %>
                          <%end%>
                        <% end %>
                      </div>
                      <div class="down-content">
                        <div class="date">
                          <h6><%= event&.event_date&.strftime("%b") %> <span><%= event&.event_date&.strftime("%d") %></span> </h6>
                        </div>
                        <%= link_to  event_path(event) do%>
                          <h4><%= event.title %></h4>
                        <% end %>
                        <p style="width:inherit ; white-space: nowrap; overflow: hidden; text-overflow:ellipsis;" > <%= event.description %> </p>
                      </div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
       
      </section>
    <% end %>
  </div>
  <div class="d-flex justify-content-center mb-3"><%= paginate @events%></div>
</div>

web4-app/assignments/app/views/events/edit.html.erb
<div class="container">
  <% if flash.any?%>
    <%= render 'layouts/alerts'%>
  <% end %>
  <br>
  <div class= "col-md-6 offset-md-3 mb-5">
    <div class="card">
      <div class="card-body">
        <h3 class="text-uppercase text-center">Edit Event</h3>
        <%= render 'form', event: @event%>
      </div>
    </div>
  </div>
</div>

web4-app/assignments/app/views/events/index.html.erb
<div class="container mt-3">
  <div class="d-flex flex-row-reverse mt-3 mb-3">
    <%= form_with(url: events_path, method: :get) do |form| %>
      <%= form.select :tag_id, (Tag.all.collect {|q| [ q.name, q.id]}).unshift(["All",0]),{selected: @selected_tag},{class:"input", :onchange => 'this.form.submit()', style:"padding: 10px"}%>
    <% end %>
  </div>
</div>
<%= render :partial => 'list', events: @events%>

web4-app/assignments/app/views/events/new.html.erb
<div class="container">
  <% if flash.any?%>
    <%= render 'layouts/alerts'%>
  <% end %>
  <br>
  <div class= "col-md-6 offset-md-3 mb-5">
    <div class="card">
      <div class="card-body">
        <h3 class="text-uppercase text-center">Create Event</h3>
        <%= render 'form', event: @event%>
      </div>
    </div>
  </div>
</div>

web4-app/assignments/app/views/events/past_events.html.erb
<div class="container mt-3">
  <div class="d-flex flex-row-reverse mt-3 mb-3">
 
    <%= form_with(url: past_events_path, method: :get) do%>
      <%= select_month(@selected_month, {}, {onchange: 'this.form.submit()', class: "input", style: "padding: 10px"})%>
    <% end %>
  </div>
</div>
<%= render :partial => 'list', locals: {events: @events} %>

web4-app/assignments/app/views/events/show.html.erb
<div class="container">
  <section class="meetings-page" id="meetings">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 offset-md-2">
          <div class="row">
            <div class="col-lg-12">
              <div class="meeting-single-item">
                <div class="thumb">
                  <div id="carouselExampleIndicators" class="carousel slide" data-mdb-ride="carousel">
                    <div class="carousel-indicators">
                      <% if @event.pictures.attached? and @event.pictures.count > 1%>
                        <% @event.pictures.each_with_index do |picture, index| %>
                          <button
                              type="button"
                              data-mdb-target="#carouselExampleIndicators"
                              data-mdb-slide-to="<%= index %>"
                              class="<%= 'active' if index == 0 %>"
                              aria-current="true"
                              aria-label="Slide <%= index%>"
                            ></button>
                        <% end %>
                      <% end %>
                    </div>
                    <div class="carousel-inner">
                      <% if @event.pictures.attached? %>
                        <% @event.pictures.each_with_index do |picture, index| %>
                          <div class="carousel-item <%= 'active' if index == 0 %>">
                            <%= image_tag(picture ,alt: "event_image", class: "d-block event-pictures")%>
                          </div>
                        <% end %>
                      <% end %>
                    </div>
                    <% if @event.pictures.attached? and @event.pictures.count > 1%>
                      <button
                          class="carousel-control-prev"
                          type="button"
                          data-mdb-target="#carouselExampleIndicators"
                          data-mdb-slide="prev"
                        >
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                      </button>
                      <button
                          class="carousel-control-next"
                          type="button"
                          data-mdb-target="#carouselExampleIndicators"
                          data-mdb-slide="next"
                        >
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                      </button>
                    <% end %>
                  </div>
                </div>
                <div class="down-content">
                  <a href="meeting-details.html">
                    <h4><%= @event.title %></h4>
                  </a>
                  <% if @event.tag.present? %>
                    <p>Category: <%= @event.tag.name %></p>
                  <% end %>
                  <p><%= @event&.event_date&.strftime("%d %B %Y %I:%M %p") %></p>
                  <pre><%= @event.description %></pre>
                  <% if current_user&.is_admin %>
                    <div class="d-flex justify-content-end">
                      <%= link_to 'Edit', edit_event_path(@event), :class=>"btn btn-su m-2" %>
                      <%= link_to 'Delete', event_path(@event), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger m-2'%>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </section>
        </div>