web4-app/assignments/config/routes.rb
Rails.application.routes.draw do
  get 'contact/form'
  post 'contact/form', to: 'contact#create'
  root 'site#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'basics', to: 'basics#index'
  get 'admin/feedback'
  patch 'admin/feedback', to: 'admin#edit'
  delete 'admin/feedback', to: 'admin#destroy'
  get 'admin/committee'
  post 'admin/committee', to: 'admin#create'
  patch 'admin/committee', to: 'admin#edit'
  delete 'admin/committee', to: 'admin#destroy'
  get 'admin/users'
  patch 'admin/users'
  post 'admin/users'
  get 'problem-sets', to: 'site#problem_sets'
  get 'basics/news', to: 'basics#news'
  get 'basics/divide_by_zero', to: 'basics#divide_by_zero'
  get 'basics/divide', to: 'basics#divide'
  get 'basics/quotations', to: 'basics#quotations'
  post 'basics/quotations', to: 'basics#quotations'
  get 'basics/sql_tasks', to: 'basics#sql_tasks'
  get 'plan/index'
  get 'plan/profiles'
  get 'plan/user_management'
  get 'plan/documentation'
  get 'su_information', to: 'su_information#index'
  post 'su_information', to: 'su_information#create'
  patch 'su_information', to: 'su_information#edit'
  delete 'su_information', to: 'su_information#destroy'
  resources :events
  get 'past-events', to: 'events#past_events'
  get 'feedback', to: 'plan#feedback'
  post 'events/removeImage', to: "events#removeImage"
end

web4-app/assignments/app/views/layouts/_alerts.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key)%> alert-dismissible fade show">
      <%= value %>
      <button type="button" class="close" data-mdb-dismiss="alert" aria-label="Close" style = 'float: right'><i class="fas fa-times"></i></button>
    </div>
  <% end %>
</div>

web4-app/assignments/app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="text-center border-top" style="background-color:#325c52; color: #f6f1e8;">
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <div class="row mt-3">
        <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-4 text-center">
          <h6 class="text-uppercase fw-bold mb-4">
            Follow Us On
          </h6>
          <div>
            <a href="https://www.facebook.com/groups/SUAITOfficial/" class="me-4 text-reset">
              <i class="fab fa-facebook-f"></i>
            </a>
            <a href="https://www.youtube.com/user/AITstudentunion" class="me-4 text-reset">
              <i class="fab fa-youtube"></i>
            </a>
            <a href="https://www.instagram.com/aitstudentunion/" class="me-4 text-reset">
              <i class="fab fa-instagram"></i>
            </a>
          </div>
        </div>
        <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-4 text-center">
          <h6 class="text-uppercase fw-bold mb-4">
            Contact
          </h6>
          <p><i class="fas fa-home me-3"></i> P.O. Box 4 58 Moo 9, Km. 42, Paholyothin Highway, Klong Luang, Pathum Thani 12120 Thailand</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            supresident@ait.asia
          </p>
        </div>
        <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-md-0 mb-4 text-center">
          <h6 class="text-uppercase fw-bold mb-4">
            Call Us
          </h6>
          <p><i class="fas fa-phone me-3"></i>(+66) 25245000</p>
          <p><i class="fas fa-print me-3"></i>(+66) 25160110-44</p>
        </div>
      </div>
    </div>
  </section>
  <!-- Copyright -->
  <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2021 Copyright: AIT Student Union
  </div>
  <!-- Copyright -->
</footer>
<!-- Footer -->

web4-app/assignments/app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-white fixed-top">
  <div class="container container-fluid">
    <button
            class="navbar-toggler"
            type="button"
            data-mdb-toggle="collapse"
            data-mdb-target="#navbar"
            aria-controls="navbar"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <%= link_to root_path, class: 'navbar-brand mt-2 mt-lg-0' do%>
        <%= image_tag "SU Logo.png",alt: "logo", loading: "lazy", class: "logo"%>
      <% end %>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 ">
        <%= link_to 'Home', root_path, class:"nav-link"%>
        <% if current_user&.is_admin %>
          <li class="nav-item dropdown">
            <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
              Admin
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li>
                <%= link_to "Admin Users", admin_users_path, class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to "Committees", admin_committee_path, class: 'dropdown-item' %>
              </li>
              <li>
                <%= link_to "Feedback", admin_feedback_path, class: 'dropdown-item' %>
              </li>
            </ul>
          </li>
        <% end %>
        <li class="nav-item">
          <%= link_to "SU Information", su_information_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact SU", contact_form_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Problem Sets", problem_sets_path, class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-mdb-toggle="dropdown"
            aria-expanded="false"
          >
            Events
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li>
              <%= link_to "Current Events", events_path, class: 'dropdown-item' %>
            </li>
            <li>
              <%= link_to "Past Events", past_events_path, class: 'dropdown-item' %>
            </li>
            <% if current_user&.is_admin %>
              <li>
                <%= link_to new_event_path, class: 'dropdown-item' do%>
                  Create Event
                <% end %>
              </li>
            <% end %>
          </ul>
        </li>
      </ul>
      <div id="user_status">
        <% if user_signed_in? %>
          Welcome <%= current_user.email %>!&nbsp;&nbsp;
          <%= link_to "Sign out", destroy_user_session_path, class: "btn btn-su", method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: "btn btn-su" %>&nbsp;&nbsp;
          <%= link_to "Sign in", new_user_session_path, class: "btn btn-su" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>

web4-app/assignments/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AIT Student Union</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%# <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script> %>
  </head>
  <body style="background-color:#FFFBF5" >
    <%= render 'layouts/header' %>
    <%# <div class="container" style= "padding-bottom: 2.5rem;"> %>
    <%= yield %>
    <%# </div> %>
    <%= render 'layouts/footer' %>
  </body>
</html>