web4-app/assignments/config/routes.rb
Rails.application.routes.draw do
  get 'contact/form'
  post 'contact/form', to: 'contact#create'
  root 'site#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'basics', to: 'basics#index'
  get 'admin/feedback'
  patch 'admin/feedback', to: 'admin#edit'
  delete 'admin/feedback', to: 'admin#destroy'
  get 'admin/committee'
  post 'admin/committee', to: 'admin#create'
  patch 'admin/committee', to: 'admin#edit'
  delete 'admin/committee', to: 'admin#destroy'
  get 'admin/users'
  patch 'admin/users'
  post 'admin/users'
  get 'problem-sets', to: 'site#problem_sets'
  get 'basics/news', to: 'basics#news'
  get 'basics/divide_by_zero', to: 'basics#divide_by_zero'
  get 'basics/divide', to: 'basics#divide'
  get 'basics/quotations', to: 'basics#quotations'
  post 'basics/quotations', to: 'basics#quotations'
  get 'basics/sql_tasks', to: 'basics#sql_tasks'
  get 'plan/index'
  get 'plan/profiles'
  get 'plan/user_management'
  get 'plan/documentation'
  get 'su_information', to: 'su_information#index'
  post 'su_information', to: 'su_information#create'
  patch 'su_information', to: 'su_information#edit'
  delete 'su_information', to: 'su_information#destroy'
  resources :events
  get 'past-events', to: 'events#past_events'
  get 'feedback', to: 'plan#feedback'
  post 'events/removeImage', to: "events#removeImage"
end

web4-app/assignments/app/controllers/basics_controller.rb
require 'nokogiri'
require 'open-uri'
require 'pry'

class BasicsController < ApplicationController
  skip_before_action :verify_authenticity_token
  def parse_ktm_news
    url = 'https://kathmandupost.com/world'
    html = URI.open(url)
    doc = Nokogiri::HTML(html)
    headers = doc.xpath("//div[@class='block--morenews']/article/a/h3")
    links = doc.xpath("//div[@class='block--morenews']/article/a/@href")
    images = doc.xpath("//div[@class='block--morenews']/article/div/figure/a/img/@data-src")
    content = doc.xpath("//div[@class='block--morenews']/article/p")

    news = []

    # binding.pry
    (0..headers.count - 1).each do |i|
      h = {}
      h[:header] = headers[i] ? headers[i].text : ''
      h[:link] = links[i] ? ('https://kathmandupost.com' + links[i].text) : ''
      h[:image] = images[i] ? images[i].text : ''
      h[:content] = content[i] ? content[i].text : ''
      news << h
    end
    news
  end

  def parse_ny_news
    headers = []
    links = []
    images = []
    content = []

    url = 'https://www.nytimes.com/international/section/world'
    html = URI.open(url)
    doc = Nokogiri::HTML(html)
    headers1 = doc.xpath("//div[@class='css-gfgt40 ekkqrpp1']//article//h2/a")
    headers2 = doc.xpath("//li[@class='css-ye6x8s']//a/h2")
    links1 = doc.xpath("//div[@class='css-gfgt40 ekkqrpp1']//article//h2//a/@href")
    links2 = doc.xpath("//li[@class='css-ye6x8s']/div/div/a/@href")
    images1 = doc.xpath("//div[@class='css-gfgt40 ekkqrpp1']//article//figure/a/img/@src")
    images2 = doc.xpath("//li[@class='css-ye6x8s']//a//figure//img/@src")
    content1 = doc.xpath("//div[@class='css-gfgt40 ekkqrpp1']//article//p[@class='css-tskdi9 e4e4i5l4']")
    content2 = doc.xpath("//li[@class='css-ye6x8s']//a/p")
    headers = headers1 + headers2
    links = links1 + links2
    images = images1 + images2
    content = content1 + content2

    # binding.pry

    news = []
    (0..headers.count - 1).each do |i|
      h = {}
      h[:header] = headers[i] ? headers[i].text : ''
      h[:link] = links[i] ? ('https://www.nytimes.com' + links[i].text) : ''
      h[:image] = images[i] ? images[i].text : ''
      # h[:content] = content[i] ?(content[i].text):''
      news << h
    end
    news
  end

  def news
    @ktm_news = parse_ktm_news
    @ny_news = parse_ny_news
  end

  def divide
    Rails.logger.warn 'About to divide by 0'
    4 / 0
  rescue StandardError => e
    @error_msg = e.message
    @stack_trace = e.backtrace
  end

  def index; end

  def killCookie
    cookies.delete :quotations_id if params[:restore]
  end

  def quotations
    @quotation = Quotation.new

    killCookie

    if params[:quotation_id]
      if cookies[:quotations_id]
        values = []
        cookies[:quotations_id].split('&').each do |i|
          values << i
        end
        values << params[:quotation_id]
        cookies[:quotations_id] = values.join(',')
      else
        cookies[:quotations_id] = params[:quotation_id]
      end
    end

    if params[:quotation]
      @quotation = if params[:quotation][:newcategory].present?
                     Quotation.new(author_name: params[:quotation][:author_name],
                                   category: params[:quotation][:newcategory], quote: params[:quotation][:quote])
                   else
                     Quotation.new(author_name: params[:quotation][:author_name],
                                   category: params[:quotation][:category], quote: params[:quotation][:quote])
                   end
      if @quotation.save
        flash[:notice] = 'Quotation was successfully created.'
        @quotation = Quotation.new
      end
    end

    if cookies[:quotations_id]
      @quotations = Quotation.where('id NOT IN (?)', cookies[:quotations_id].split(','))
      @cookie_exist = true
    else
      @quotations = Quotation.all
      @cookie_exist = false
    end

    if params[:search] && params[:search].present?
      @quotations = @quotations.where('author_name ILIKE ? OR quote ILIKE ?', '%' + params[:search] + '%',
                                      '%' + params[:search] + '%')
      @resp = 'No results found' if @quotations.empty?
    end
    @quotations = if params[:sort_by] == 'date'
                    @quotations.order(:created_at)
                  else
                    @quotations.order(:category)
                  end

    export_data
    import_data
  end

  def export_data
    # Code to download the the JSON and XML files
    # if params[:export_type]
    #   if params[:export_type] == 'JSON'
    #     json_data = @quotations.to_json
    #     send_data json_data, :type => "application/json; header=present", :disposition => "attachment; filename=quotations.json"
    #   else
    #     xml_data = JSON.parse(@quotations.to_json).to_xml
    #     send_data xml_data, :type => "application/xml; header=present", :disposition => "attachment; filename=quotations.xml"
    #   end
    # end
    respond_to do |format|
      format.html
      format.xml { render xml: @quotations.as_json }
      format.json { render json: @quotations }
    end
  end

  def import_data
    if params[:import_link].present?
      begin
        response = URI.open(params[:import_link]).string
      rescue StandardError => e
        Rails.logger.info('Could not import from the link')
        response = ''
      end
      xml_content = Nokogiri::XML(response)
      xml_content.css('object').each do |tag|
        children = tag.children
        @quotation = Quotation.new(author_name: children.css('author-name').inner_text,
                                   category: children.css('category').inner_text, quote: children.css('quote').inner_text)
        @quotation.save
      end
    end
  end
end

web4-app/assignments/app/helpers/basics_helper.rb
module BasicsHelper
end

web4-app/assignments/app/views/basics/divide.html.erb
<div class="container">
  <h3>Stack Trace</h3>
  <p>Error Message: <%= @error_msg%></p>
  <br>
  <p><%= @stack_trace %></p>
</div>

web4-app/assignments/app/views/basics/divide_by_zero.html.erb
<div class="container">
  <h3>Divide by zero</h3>
  <hr>
  <div class="mb-3">
    <%= button_to 'Divide', basics_divide_path, class: 'btn btn-success', method: :get %>
  </div>
  <h5>Explanation</h5>
  <p>
    The button above when clicked calls a method which divides 4 by 0 and raises divide by zero exception.<br>
    <br>
    Using <i>Rails.logger.warn</i> we added "About to divide by 0" warning in the log before the exception occurs as shown in the screen shot below.
    The divide by zero exception was handled to get the error message and the stack trace. 
  </p>
  <p>Screen shot of production log</p>
  <%= image_tag "log.png",alt: "log_image", class: "_image"%>
</div>

web4-app/assignments/app/views/basics/news.html.erb
<div class="container">
  <div class = "row">
    <div class="col-md-6">
      <h4 style="text-align: center">The kathmandu Post News</h4>
      <% @ktm_news.each do |news| %>
        <div class="card p-5">
          <a href=<%= news[:link] %>>
            <h5><%= news[:header] %></h5>
          </a>
          <img src=<%= news[:image]%> alt="image" width=100% height=265>
          <p><%= news[:content]%></p>
        </div>
      <% end %>
    </div>
    <div class="col-md-6">
      <h4 style="text-align: center">The New York Times News</h4>
      <% @ny_news.each do |news| %>
        <div class="card p-5">
          <a href=<%= news[:link] %>>
            <h5><%= news[:header] %></h5>
          </a>
          <img src=<%= news[:image]%> alt="image" width=100% height=265>
          <p><%= news[:content]%></p>
        </div>
      <% end %>
    </div>
  </div>
</div>

web4-app/assignments/app/views/basics/quotations.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h5>Search quote</h5>
      <%= form_tag(basics_quotations_path, method: :get) do%>
        <%= text_field_tag(:search, params[:search])%>
        <%= submit_tag("Search")%>
      <% end %>
    </div>
    <div class="col-md-6">
      <div class="row">
        <div class="col-md-6">
          <h5>Import XML</h5>
          <%= form_tag(basics_quotations_path, method: :post) do%>
            <%= text_field_tag(:import_link, params[:import_link])%>
            <%= submit_tag("Import")%>
          <% end %>
        </div>
        <div class="col-md-6 mt-4">
          <%= link_to "Export JSON", :action => :quotations, :format=>'json' %>
          <%= link_to "Export XML", :action => :quotations, :format=>'xml' %>
        </div>
      </div>
    </div>
  </div>
  <br/>
  <h3>Quotations</h3>
  <table class= "table table-striped table-bordered table-hover">
    <thead style = "background-color:#506477; color:white">
      <tr>
        <th>Author</th>
        <th>Quote</th>
        <th colspan="1"></th>
      </tr>
    </thead>
    <tbody>
      <% if @quotations.each do |quotation| %>
        <tr>
          <td><%= quotation.author_name %></td>
          <td><%= quotation.quote %></td>
          <td><%= link_to 'delete', :action => :quotations, :quotation_id =>  quotation.id%></td>
        </tr>
      <% end.empty? %>
      <tr>
        <td colspan="3" style="text-align:center"><%= @resp %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br/>
<div class="row">
  <% if params[:sort_by] == "date" %>
    <%= link_to "Sort by category",:action => :quotations, :sort_by => :category %>
  <% else %>
    <%= link_to "Sort by date",:action => :quotations, :sort_by => :date %>
  <% end %>
  <% if @cookie_exist %>
    <%= link_to "Restore", :action => :quotations, :restore => ''%>
  <% end %>
</div>
<hr/>
<h3>New quotation</h3>
<br>
<%= form_for @quotation, :url => { :action => :quotations } do |form| %>
  <% @quotation.errors.full_messages.each do |msg| %>
    <div class="alert alert-warning alert-dismissible fade show col-6" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
  <fieldset>
    <legend>Enter details</legend>
    <div class="form_row col-4">
      <% form.label :author_name %>
      <%= form.text_field :author_name, class:"form-control" , placeholder: :author_name%>
    </div>
    <br>
    <div class="form-group row col-5" >
      <%= form.label 'Category: ', class:"col-sm-2 col-form-label"%>
      <div class="col-sm-8">
        <% if @quotations %>
          <%= form.select( :category, @quotations.collect {|q| [ q.category] }.uniq,{}, {class:"form-select"})%>
        <% else %>
          <%= form.select( :category, {},{}, {class:"form-select"})%>
        <% end %>
      </div>
    </div>
    <br>
    <div class="form_row col-4">
      <% form.label :category %>
      <%= form.text_field :newcategory, class:"form-control", placeholder: 'New Category' %>
    </div>
    <br>
    <div class="form_row col-6">
      <%= form.label :quote %>
      <%= form.text_area :quote , class:"form-control"%>
    </div>
  </fieldset>
  <p>
    <div class="form-row">
      <%= form.submit 'Create', class: "btn btn-secondary"%>
    </div>
  </p>
<% end %>
<hr>
<p class="mb-0">References :
  <a style="font-size:14px" href="https://www.rubyguides.com/2019/07/rails-where-method/">Rails Where Method</a>&nbsp;&nbsp;
  <a style="font-size:14px" href="https://api.rubyonrails.org/v5.2.1/classes/ActionDispatch/Cookies.html">Rails Cookies</a>&nbsp;&nbsp;
  <a style="font-size:14px" href="https://api.rubyonrails.org/classes/ActionController/MimeResponds.html">Rails ActionController</a>&nbsp;&nbsp;
</p>
</div>

web4-app/assignments/app/views/basics/sql_tasks.html.erb
<div class="container">
  <a href="<%= asset_url('ps2_db_transcript.txt') %>" target="_blank" > Transcript File</a>
  <p class="mb-0">References :
    <a style="font-size:14px" href="https://www.postgresql.org/docs/current/sql-copy.html">Postgresql copy data</a>&nbsp;&nbsp;
    <a style="font-size:14px" href="https://www.postgresql.org/docs/13/plpgsql-porting.html#id-1.8.8.15.6">PL/pgSQL Functions</a>&nbsp;&nbsp;
    <a style="font-size:14px" href="https://www.postgresql.org/docs/13/plpgsql-cursors.html">PL/pgSQL Cursor</a>&nbsp;&nbsp;
    <a style="font-size:14px" href="https://www.postgresql.org/docs/9.4/functions-string.html">Postrgresql ASCII</a>&nbsp;&nbsp;
    <a style="font-size:14px" href="https://www.postgresql.org/docs/9.2/sql-createview.html">Postgresql view</a>&nbsp;&nbsp;
  </p>
</div>