web4-app/assignments/config/routes.rb
Rails.application.routes.draw do
  get 'contact/form'
  post 'contact/form', to: 'contact#create'
  root 'site#index'
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth', registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  # get 'basics', to: 'basics#index'
  get 'admin/feedback'
  patch 'admin/feedback', to: 'admin#edit'
  delete 'admin/feedback', to: 'admin#destroy'
  get 'admin/committee'
  post 'admin/committee', to: 'admin#create'
  patch 'admin/committee', to: 'admin#edit'
  delete 'admin/committee', to: 'admin#destroy'
  get 'admin/users'
  patch 'admin/users'
  post 'admin/users'
  get 'problem-sets', to: 'site#problem_sets'
  get 'basics/news', to: 'basics#news'
  get 'basics/divide_by_zero', to: 'basics#divide_by_zero'
  get 'basics/divide', to: 'basics#divide'
  get 'basics/quotations', to: 'basics#quotations'
  post 'basics/quotations', to: 'basics#quotations'
  get 'basics/sql_tasks', to: 'basics#sql_tasks'
  get 'plan/index'
  get 'plan/profiles'
  get 'plan/user_management'
  get 'plan/documentation'
  get 'su_information', to: 'su_information#index'
  post 'su_information', to: 'su_information#create'
  patch 'su_information', to: 'su_information#edit'
  delete 'su_information', to: 'su_information#destroy'
  resources :events
  get 'past-events', to: 'events#past_events'
  get 'feedback', to: 'plan#feedback'
  post 'events/removeImage', to: "events#removeImage"
end

web4-app/assignments/app/controllers/site_controller.rb
class SiteController < ApplicationController
    def index 
        @events = Event.where('event_date >= ?', Date.today ).order('event_date DESC').last(4)
    end
end

web4-app/assignments/app/helpers/site_helper.rb
module SiteHelper
end

web4-app/assignments/app/views/site/index.html.erb
<div
          id="ait-background"
          class="p-5 text-center bg-image"
          style="background-image: url(<%= asset_path 'background.jpg' %>);"
  >
  <div class="mask" style="background-color: rgba(0, 0, 0, 0.7);">
    <div class="d-flex justify-content-center align-items-center h-100">
      <div class="text-white">
        <%= link_to 'View Events', events_path , class: "btn btn-outline-light btn-lg m-2", role: "button"%>
        <%= link_to 'Register Complain', contact_form_path , class: "btn btn-outline-light btn-lg m-2", role: "button"%>
      </div>
    </div>
  </div>
</div>
<% if @events.present? %>
  <div class="container mt-5">
    <div class="d-flex justify-content-between mb-4">
      <h5 class = "text-uppercase fw-bold ">Event Highlights</h5>
      <%= link_to  events_path, class: "btn btn-su" do%>
        More Events &nbsp;&nbsp; <i class="fas fa-arrow-right"></i>
      <% end %>
    </div>
    <div class="row">
      <% @events.each do |event| %>
        <div class="col-md-3 mb-5">
          <div class="su-card">
            <%= link_to event_path(event), style: "display: block;" do%>
              <div class="su-card-header card-header">
                <% if event.pictures.attached? %>
                  <%= image_tag(event.pictures.first,alt: "event_image", class: "img-fluid", style: "width: 100%; max-height: 175px;")%>
                <% end %>
                <div class="card-header_overlay text-center">
                  <span class="pill"><%= event.title %></span>
                </div>
              </div>
              <div class="page-header text-center" style="padding-top:5px;">
                <p><%= event&.event_date&.strftime("%d %B %Y %I:%M %p") %></p>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

web4-app/assignments/app/views/site/problem_sets.html.erb
<div class="container">
  <%= flash[:message] %>
  <div class="row">
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-header">Problem Set 1: Basics</h5>
          <p class="card-text">
            <ul>
              <li>
                <p><%= link_to 'Divide by zero', basics_divide_by_zero_path%></p>
              </li>
              <li>
                <p><%= link_to 'News', basics_news_path%></p>
              </li>
            </ul>
            <p class="mb-0">Online references :
              <a style="font-size:14px" href="https://www.zyte.com/blog/an-introduction-to-xpath-with-examples/#:~:text=XPath%20is%20a%20powerful%20language,extract%20web%20data%20using%20Scrapy.">Intro to Xpath</a>&nbsp;&nbsp;
              <a style="font-size:14px" href="https://medium.com/@jennyjean8675309/web-scraping-with-ruby-and-nokogiri-73e75a6f34ed">Web Scraping with Nokogiri</a>&nbsp;&nbsp;
              <a style="font-size:14px" href="https://stackify.com/rails-logger-and-rails-logging-best-practices/">Rails Logger</a>
            </p>
            <p>News website:
              <a style="font-size:14px" href="https://kathmandupost.com/">The Kathmandu Post</a>&nbsp;&nbsp;
              <a style="font-size:14px" href="https://www.nytimes.com/">The New York Times</a>
            </p>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-header">Problem Set 2: Basics</h5>
          <p class="card-text">
            <ul>
              <li>
                <p><%= link_to 'Quotations', basics_quotations_path%></p>
              </li>
              <li>
                <p><%= link_to 'SQL Tasks', basics_sql_tasks_path%></p>
              </li>
            </ul>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-header">Problem Set 3: Planning, Odds and Ends</h5>
          <p class="card-text">
            <ul>
              <li>
                <p><%= link_to 'Project Plan', plan_index_path%></p>
              </li>
              <li>
                <p><%= link_to 'Profile Pages', plan_profiles_path%></p>
              </li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-4" >
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-header">Problem Set 4: Odds, Ends, and User Management</h5>
          <p class="card-text">
            <ul>
              <li>
                <p><%= link_to 'User Management', plan_user_management_path%></p>
              </li>
              <li>
                <p><%= link_to 'Database Dump', asset_url('db_backup_20211016113301.psql'), target: "_blank" %></p>
              </li>
            </ul>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4" >
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-header">Problem Set 5: Content Management, Part I</h5>
          <p class="card-text">
            <ul>
              <li>
                <p><%= link_to 'Documentation', plan_documentation_path%></p>
              </li>
            </ul>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-4" >
      <div class="card mb-4">
        <div class="card-body">
          <h5 class="card-header">Problem Set 6: User Evaluation</h5>
          <p class="card-text">
            <ul>
              <li>
                <p><%= link_to "User Evaluation", asset_path("evaluation.pdf"), target: "_blank" %></p>
              </li>
              <li>
                <p><%= link_to "Feedback and Action Plan", feedback_path %></p>
              </li>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>